/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package encrypt;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Puneet_Gupta_1
 */
public class LoginGui2 extends javax.swing.JFrame {

    /**
     * Creates new form LoginGui2
     */
    public LoginGui2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf1 = new javax.swing.JTextField();
        pf1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tf1.setBackground(java.awt.SystemColor.controlDkShadow);
        tf1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        tf1.setForeground(new java.awt.Color(153, 255, 255));
        tf1.setToolTipText("Enter Username");
        getContentPane().add(tf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 190, 50));

        pf1.setBackground(new java.awt.Color(102, 102, 102));
        pf1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        pf1.setForeground(new java.awt.Color(102, 255, 255));
        pf1.setToolTipText("Enter Password");
        getContentPane().add(pf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 180, 50));

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 90, 50));

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setText("New User");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 120, 30));

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setForeground(new java.awt.Color(153, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/encrypt/pot1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String username=tf1.getText();
        String password = new String(pf1.getPassword());
       // System.out.println(password);
        String duser="hola",dpass;
        int flag=1,flag2=1;
        Connection con=null;
        try{
            String url="jdbc:mysql://localhost:3306/hello?useSSL=false";
            String user="root";
            String pass="1234";
            con=DriverManager.getConnection(url,user,pass);
            Statement stmt=con.createStatement();
            String query="select * from user";
            ResultSet rs=stmt.executeQuery(query);
            //System.out.println("so far so good 1");
            while(rs.next())
            {
                duser=rs.getString(1);
                if(duser.equals(username))
                {
                    flag2=0;
                    dpass=rs.getString(2);
                    if(dpass.equals(password))
                    {
                       JOptionPane.showMessageDialog(this,"Login Success");
                       flag=0;
                       break;
                    }  
                }
                //System.out.print(rs.getString(1)+" "+rs.getString(2)+"\n");
            }
            if(flag2==1)
                JOptionPane.showMessageDialog(this,"Uregistered User");
            if(flag==1 && flag2==0)
                JOptionPane.showMessageDialog(this,"Wrong Password");
            if(flag==0&&flag2==0)
            {
                
                NewJFrame ma = new NewJFrame(duser);
                ma.setVisible(true);
                this.dispose();
                
            }
        }catch(SQLException e)
        {
            System.out.println(e.getMessage());
        }
        finally{
            try{
                if(con!=null)
                con.close();
        }catch(SQLException e)
        {
            System.out.println(e.getMessage());
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new AdduserGUI().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginGui2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginGui2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginGui2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginGui2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginGui2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField pf1;
    private javax.swing.JTextField tf1;
    // End of variables declaration//GEN-END:variables
}
