/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package encrypt;

import javax.swing.JFileChooser;
import java.io.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Puneet_Gupta_1
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }
        public NewJFrame(String user){
        initComponents();
        usern=user;
        this.setTitle("Welcome "+user);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FileChooser = new javax.swing.JFileChooser();
        path = new javax.swing.JTextField();
        b1 = new javax.swing.JButton();
        t2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("File Encrypter App");
        setBackground(new java.awt.Color(102, 255, 102));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        path.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        path.setToolTipText("Type the path or choose a file");
        path.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pathMouseClicked(evt);
            }
        });

        b1.setBackground(new java.awt.Color(0, 204, 204));
        b1.setText("Choose File");
        b1.setToolTipText("Or type the path");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        t2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t2MouseClicked(evt);
            }
        });

        jLabel1.setText("Enter Name of new file");

        t3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t3MouseClicked(evt);
            }
        });

        jLabel2.setText("Enter the key");

        jButton1.setBackground(new java.awt.Color(51, 255, 255));
        jButton1.setText("Encrypt ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 255, 0));
        jButton2.setText("Decrypt");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(102, 231, 235));
        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 204, 204));
        jButton5.setText("Encrypt using S-AES");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(0, 204, 0));
        jButton6.setText("Decrypt S-AES ");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Exit");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Edit");

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Clear All");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("History");

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setText("App History");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Add User");

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setText("New User");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem7);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("View");

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setText("Registered User");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem8);

        jMenuBar1.add(jMenu6);

        jMenu2.setText("Help");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem1.setText("Help");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);
        jMenu2.add(jSeparator1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("About");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Developers");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(t2)
                            .addComponent(path)
                            .addComponent(t3))
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b1))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        String pstr="";
        File file=null;
        long size=0;
        int retVal=FileChooser.showOpenDialog(this);
        if(retVal==JFileChooser.APPROVE_OPTION)
        {
            file=FileChooser.getSelectedFile();
            pstr=file.getAbsolutePath();
            size=file.length();
            fsize=Long.toString(size);
        }
        //System.out.println(""+size);
        if(pstr.length()!=0)
            path.setText(pstr);
    }//GEN-LAST:event_b1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        path.setText("");
        t2.setText("");
        t3.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String str,nstr,npath = null,t;
        str=path.getText();
        if(str.length()!=0)
        {
            int i=str.lastIndexOf('\\')+1;
            nstr=str.substring(0,i);
            t=t2.getText();
            npath=nstr+t;
            System.out.println(""+npath);
        }
        int key=Integer.parseInt(t3.getText());
        if(key>0&&key<=25)
        {
        FileInputStream in =null;
        FileOutputStream out=null;
        try{
            in=new FileInputStream(str);
            out = new FileOutputStream(npath);
            int c;
            while((c=in.read())!=-1)
            {
                out.write((c+key)%256);
            }
            JOptionPane.showMessageDialog(this,"File Encrypted");
        }
        catch(IOException ae){
            System.out.println(""+ae);
        }
        finally
        {
            try
            {
            if(in!=null)
                in.close();
            if(out!=null)
                out.close();
            }
            catch(IOException ae)
            {
                System.out.println(""+ae);
            }
        }}
        else
        {
            JOptionPane.showMessageDialog(this,"Enter Key Between 1 and 25","Range Error",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String str,nstr,npath = null,t;
        str=path.getText();
        if(str.length()!=0)
        {
            int i=str.lastIndexOf('\\')+1;
            nstr=str.substring(0,i);
            t=t2.getText();
            npath=nstr+t;
            System.out.println(""+npath);
        }
        int key=256-Integer.parseInt(t3.getText());
        
        FileInputStream in =null;
        FileOutputStream out=null;
        try{
            in=new FileInputStream(str);
            out = new FileOutputStream(npath);
            int c;
            while((c=in.read())!=-1)
            {
                out.write((c+key)%256);
            }
            JOptionPane.showMessageDialog(this,"File Decrypted");
        }
        catch(IOException ae){
            System.out.println(""+ae);
        }
        finally
        {
            try
            {
            if(in!=null)
                in.close();
            if(out!=null)
                out.close();
            }
            catch(IOException ae)
            {
                System.out.println(""+ae);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    String filename,nfilename,fsize,usern;
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        String str,nstr="",npath = null,t="",keyl,keyj;
        str=path.getText();
        keyl=t2.getText();
        keyj=t3.getText();
        
        if(str.length()==0||keyl.length()==0||keyj.length()==0)
        {
            JOptionPane.showMessageDialog(this,"Fill all fields");
            
        }else{
        int i=0;
        if(str.length()!=0)
        {
            i=str.lastIndexOf('\\')+1;
            nstr=str.substring(0,i);
            t=t2.getText();
            npath=nstr+t;
            System.out.println(""+npath);
        }
        int key1=Integer.parseInt(t3.getText());
        
        filename=str.substring(i);
        nfilename=t;
       // System.out.println(""+filename+" "+nfilename+" "+fsize);
        //Here on the algorithm starts
        
        if(key1>=0&&key1<=65535){
        int subnib[]=new int[16];
		subnib[0]=9;
		subnib[1]=4;
		subnib[2]=10;
		subnib[3]=11;
		subnib[4]=13;
		subnib[5]=1;
		subnib[6]=8;
		subnib[7]=5;
		subnib[8]=6;
		subnib[9]=2;
		subnib[10]=0;
		subnib[11]=3;
		subnib[12]=12;
		subnib[13]=14;
		subnib[14]=15;
		subnib[15]=7;
		
		int t4[] = new int[16];
		t4[0]=0;t4[1]=4;t4[2]=8;t4[3]=12;
		t4[4]=3;t4[5]=7;t4[6]=11;t4[7]=15;
		t4[8]=6;t4[9]=2;t4[10]=14;t4[11]=10;
		t4[12]=5;t4[13]=1;t4[14]=13;t4[15]=9;
		
		int key=key1;
		
		int w0[]=new int[2];
		int w1[]=new int[2];
		int w2[]=new int[2];
		int w3[]=new int[2];
		int w4[]=new int[2];
		int w5[]=new int[2];
		
		int step=15;
		w1[1]=(key&step);step=step<<4;	
		w1[0]=(key&step);step=step<<4;w1[0]=w1[0]>>4;
		
		w0[1]=(key&step);step=step<<4;w0[1]=w0[1]>>8;
		w0[0]=(key&step);step=step<<4;w0[0]=w0[0]>>12;
		
		w2[1]=w0[1]^0^(subnib[w1[0]]);
		w2[0]=w0[0]^8^(subnib[w1[1]]);
		
		w3[1]=w2[1]^w1[1];
		w3[0]=w2[0]^w1[0];
		
		w4[1]=w2[1]^0^(subnib[w3[0]]);
		w4[0]=w2[0]^3^(subnib[w3[1]]);
		
		w5[1]=w4[1]^w3[1];
		w5[0]=w4[0]^w3[0];
                
                
        //till here pre declaration
        FileInputStream in =null;
        FileOutputStream out=null;
        try{
            in=new FileInputStream(str);
            out = new FileOutputStream(npath);
            int c,d;
            while((c=in.read())!=-1)
            {
                d=in.read();
                if(d==-1)
                    d=0;
                int p1=c,p2=d;
		int plaint;
		plaint=(p1<<8)|p2;
		int p[]=new int[4];
		step=15;
		p[3]=(plaint & step);step=step<<4;
		p[2]=(plaint & step);step=step<<4;p[2]=p[2]>>4;
		p[1]=(plaint & step);step=step<<4;p[1]=p[1]>>8;
		p[0]=(plaint & step);step=step<<4;p[0]=p[0]>>12;
		
		
		//S-Aes encryption round 0 preround key adding
		
		p[0]=p[0]^w0[0];p[1]=p[1]^w0[1];
		p[2]=p[2]^w1[0];p[3]=p[3]^w1[1];
		
		// Start of Round 1
		// nibble substitution
		
		p[0]=subnib[p[0]];
		p[1]=subnib[p[1]];
		p[2]=subnib[p[2]];
		p[3]=subnib[p[3]];
		
		int temp;
		
		//row shifting
		temp=p[1];
		p[1]=p[3];
		p[3]=temp;
		
		//column mixing
		int s[]=new int[4];
		
		s[0]=p[0]^t4[p[1]];
		s[1]=t4[p[0]]^p[1];
		s[2]=p[2]^t4[p[3]];
		s[3]=t4[p[2]]^p[3];
		
		//add round 1 key
		
		s[0]=s[0]^w2[0];s[1]=s[1]^w2[1];
		s[2]=s[2]^w3[0];s[3]=s[3]^w3[1];
		
		//Final Round
		//nibble substitution
		s[0]=subnib[s[0]];
		s[1]=subnib[s[1]];
		s[2]=subnib[s[2]];
		s[3]=subnib[s[3]];
		
		//row shifting
		temp=s[1];
		s[1]=s[3];
		s[3]=temp;
		
		//add 2nd round key
		s[0]=s[0]^w4[0];s[1]=s[1]^w4[1];
		s[2]=s[2]^w5[0];s[3]=s[3]^w5[1];
		
		//Encryption complete
		int o1,o2;
		o1=(s[0]<<4)|s[1];
		o2=(s[2]<<4)|s[3];
                out.write(o1);
                out.write(o2);
//		int cyph=s[3]|(s[2]<<4)|(s[1]<<8)|(s[0]<<12);
		//System.out.println(""+o1+" "+o2);
		//System.out.println(" "+s[0]+" "+s[1]+" "+s[2]+" "+s[3]);
		
            }
            JOptionPane.showMessageDialog(this,"File Encrypted");
            DateFormat dateFormat=new SimpleDateFormat("yyy/MM/dd HH:mm:ss");
        Date date = new Date();
        String strd=dateFormat.format(date);
        SqlUpdate sup=new SqlUpdate();
        sup.insert(usern,filename,fsize,nfilename,strd);
        
        }
        catch(IOException ae){
            System.out.println(""+ae);
        }
        finally
        {
            try
            {
            if(in!=null)
                in.close();
            if(out!=null)
                out.close();
            }
            catch(IOException ae)
            {
                System.out.println(""+ae);
            }
        }
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Enter Key Between 0 and 65535","Range Error",JOptionPane.ERROR_MESSAGE);
        }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    String str,nstr,npath = null,t="",keyl,keyj;
        str=path.getText();
         int i=0;
        keyl=t2.getText();
        keyj=t3.getText();
        
        if(str.length()==0||keyl.length()==0||keyj.length()==0)
        {
            JOptionPane.showMessageDialog(this,"Fill all fields");
            
        }else{
        if(str.length()!=0)
        {
            i=str.lastIndexOf('\\')+1;
            nstr=str.substring(0,i);
            t=t2.getText();
            npath=nstr+t;
            System.out.println(""+npath);
        }
        int key=Integer.parseInt(t3.getText());
        
         filename=str.substring(i);
        nfilename=t;
        
        int chk=1;
        int o11,o22;
		int subsnib[]=new int[16];
		int invsubsnib[]=new int[16];
		int y1[]=new int[16];
		int t9[]=new int[16];

		int kei=key;
		
		int w00[]=new int[2];
		int w11[]=new int[2];
		int w22[]=new int[2];
		int w33[]=new int[2];
		int w44[]=new int[2];
		int w55[]=new int[2];
		
		int stepp=15;
		
		int p11,p22;
		int pq[]=new int[4];
		int plant;
		int s1[]=new int[4];
		
		
		subsnib[0]=9;     invsubsnib[9]=0;
		subsnib[1]=4;     invsubsnib[4]=1;
		subsnib[2]=10;    invsubsnib[10]=2;
		subsnib[3]=11;    invsubsnib[11]=3;
		subsnib[4]=13;    invsubsnib[13]=4;
		subsnib[5]=1;     invsubsnib[1]=5;
		subsnib[6]=8;     invsubsnib[8]=6;
		subsnib[7]=5;     invsubsnib[5]=7;
		subsnib[8]=6;     invsubsnib[6]=8;
		subsnib[9]=2;     invsubsnib[2]=9;
		subsnib[10]=0;    invsubsnib[0]=10;
		subsnib[11]=3;    invsubsnib[3]=11;
		subsnib[12]=12;   invsubsnib[12]=12;
		subsnib[13]=14;   invsubsnib[14]=13;
		subsnib[14]=15;   invsubsnib[15]=14;
		subsnib[15]=7;    invsubsnib[7]=15;
		
		
		y1[0]=0;   y1[1]=2;  y1[2]=4;    y1[3]=6;
		y1[4]=8;   y1[5]=10; y1[6]=12;   y1[7]=14;
		y1[8]=3;   y1[9]=1;  y1[10]=7;   y1[11]=5;
		y1[12]=11; y1[13]=9; y1[14]=15;  y1[15]=13;
		
		t9[0]=0;   t9[1]=9;   t9[2]=1;    t9[3]=8;
		t9[4]=2;   t9[5]=11;  t9[6]=3;    t9[7]=10;
		t9[8]=4;   t9[9]=13;  t9[10]=5;   t9[11]=12;
		t9[12]=6;  t9[13]=15; t9[14]=7;   t9[15]=14;
		

//key generation
		w11[1]=(kei&stepp);stepp=stepp<<4;	
		w11[0]=(kei&stepp);stepp=stepp<<4;w11[0]=w11[0]>>4;
		
		w00[1]=(kei&stepp);stepp=stepp<<4;w00[1]=w00[1]>>8;
		w00[0]=(kei&stepp);stepp=stepp<<4;w00[0]=w00[0]>>12;
		
		w22[1]=w00[1]^0^(subsnib[w11[0]]);
		w22[0]=w00[0]^8^(subsnib[w11[1]]);
		
		w33[1]=w22[1]^w11[1];
		w33[0]=w22[0]^w11[0];
		
		w44[1]=w22[1]^0^(subsnib[w33[0]]);
		w44[0]=w22[0]^3^(subsnib[w33[1]]);
		
		w55[1]=w44[1]^w33[1];
		w55[0]=w44[0]^w33[0];
		
		//kei generation complete
        
        FileInputStream in =null;
        FileOutputStream out=null;
        try{
            in=new FileInputStream(str);
            out = new FileOutputStream(npath);
            int c,d=0;
            while((c=in.read())!=-1)
            {
                d=in.read();
                
                p11=c;
                p22=d;
                //input encrypted data
                plant=(p11<<8)|p22;
		
		
		stepp=15;
		pq[3]=(plant & stepp);stepp=stepp<<4;
		pq[2]=(plant & stepp);stepp=stepp<<4;pq[2]=pq[2]>>4;
		pq[1]=(plant & stepp);stepp=stepp<<4;pq[1]=pq[1]>>8;
		pq[0]=(plant & stepp);stepp=stepp<<4;pq[0]=pq[0]>>12;
		
		//Decryption
		//Add round 2 kei
		
		pq[0]=pq[0]^w44[0];pq[1]=pq[1]^w44[1];
		pq[2]=pq[2]^w55[0];pq[3]=pq[3]^w55[1];
		
		//inverse shift row
		int temp=pq[1];
		pq[1]=pq[3];
		pq[3]=temp;
		
		//inverse nibble substitution
		pq[0]=invsubsnib[pq[0]];
		pq[1]=invsubsnib[pq[1]];
		pq[2]=invsubsnib[pq[2]];
		pq[3]=invsubsnib[pq[3]];
		
		//Add round 1 kei
		pq[0]=pq[0]^w22[0];pq[1]=pq[1]^w22[1];
		pq[2]=pq[2]^w33[0];pq[3]=pq[3]^w33[1];
		
		//column inverse mixing

		
		
		s1[0]=t9[pq[0]]^y1[pq[1]];
		s1[1]=y1[pq[0]]^t9[pq[1]];
		s1[2]=t9[pq[2]]^y1[pq[3]];
		s1[3]=y1[pq[2]]^t9[pq[3]];
		
		//inverse shift row
		temp=s1[1];
		s1[1]=s1[3];
		s1[3]=temp;
		
		//inverse nibble sub
		s1[0]=invsubsnib[s1[0]];
		s1[1]=invsubsnib[s1[1]];
		s1[2]=invsubsnib[s1[2]];
		s1[3]=invsubsnib[s1[3]];
		
		//add round 0 kei
		s1[0]=s1[0]^w00[0];s1[1]=s1[1]^w00[1];
		s1[2]=s1[2]^w11[0];s1[3]=s1[3]^w11[1];
		
		int cyph=s1[3]|(s1[2]<<4)|(s1[1]<<8)|(s1[0]<<12);
		
		o11=(s1[0]<<4)|s1[1];
		o22=(s1[2]<<4)|s1[3];
                out.write(o11);
                
                if(in.available()!=0||o22!=0)
                out.write(o22);
//		System.out.println(""+o11+" "+o22);
		//System.out.println(" "+s[0]+" "+s[1]+" "+s[2]+" "+s[3]);
		
		
                
            }
            JOptionPane.showMessageDialog(this,"File Decrypted");
            
            DateFormat dateFormat=new SimpleDateFormat("yyy/MM/dd HH:mm:ss");
        Date date = new Date();
        String strd=dateFormat.format(date);
        SqlUpdate sup=new SqlUpdate();
        sup.insert(usern,filename,fsize,nfilename,strd);
        
        }
        catch(IOException ae){
            System.out.println(""+ae);
        }
        finally
        {
            try
            {
            if(in!=null)
                in.close();
            if(out!=null)
                out.close();
            }
            catch(IOException ae)
            {
                System.out.println(""+ae);
            }
        }        

        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new HelpGUI().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        new AboutGUI().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        new DevelopersGUI().setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        path.setFocusable(false);
        t2.setFocusable(false);
        t3.setFocusable(false);
    }//GEN-LAST:event_formMouseClicked

    private void pathMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pathMouseClicked
        // TODO add your handling code here:
        path.setFocusable(true);
    }//GEN-LAST:event_pathMouseClicked

    private void t2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t2MouseClicked
        // TODO add your handling code here:
       t2.setFocusable(true);
    }//GEN-LAST:event_t2MouseClicked

    private void t3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t3MouseClicked
        // TODO add your handling code here:
        t3.setFocusable(true);
    }//GEN-LAST:event_t3MouseClicked

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        path.setText("");
        t2.setText("");
        t3.setText("");
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        new HistoryGUI(usern).setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        new AdduserGUI().setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        new RegisteredGUI().setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser FileChooser;
    private javax.swing.JButton b1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextField path;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    // End of variables declaration//GEN-END:variables
}
